// examples/cloudflare-tanstack-start-solid/src/routes/index.tsx
import { createFileRoute } from "@tanstack/solid-router";
import { createServerFn } from "@tanstack/solid-start";
import { createSignal } from "solid-js";

export const getServerGreeting = createServerFn({
  method: "GET",
}).handler(() => ({
  message: "Hello from TanStack Start Solid on Cloudflare.Vite.",
}));

export const Route = createFileRoute("/")({
  loader: () => getServerGreeting(),
  component: Home,
});

function Home() {
  const initial = Route.useLoaderData();
  const [message, setMessage] = createSignal(initial().message);

  return (
    <main
      style={{
        "max-width": "720px",
        margin: "0 auto",
        padding: "4rem 1.5rem",
      }}
    >
      <h1 style={{ margin: 0, "font-size": "2.5rem" }}>TanStack Start Solid</h1>
      <p style={{ "margin-top": "1rem", "font-size": "1.125rem" }}>
        This app is served by <code>Cloudflare.Website.Vite</code>.
      </p>
      <p data-testid="server-greeting">{message()}</p>
      <button
        type="button"
        onClick={async () => {
          const next = await getServerGreeting();
          setMessage(next.message);
        }}
      >
        Refresh from server
      </button>
    </main>
  );
}

// examples/cloudflare-tanstack/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import * as Effect from "effect/Effect";
import { useState } from "react";
import Worker from "../worker.ts";

// bridge from TanstackStart to the Alchemy Effect Worker
export const worker = await Worker.initPromise();

export const getProfile = createServerFn({
  method: "GET",
}).handler(() => Effect.runPromise(worker.getProfile("John Doe")));

export const getServerTime = createServerFn({
  method: "GET",
}).handler(() => {
  return {
    message: "Hello from a TanStack Start server function.",
    time: new Date().toISOString(),
  };
});

export const Route = createFileRoute("/")({
  loader: () => getServerTime(),
  component: Home,
});

function Home() {
  const initialData = Route.useLoaderData();
  const [data, setData] = useState(initialData);

  return (
    <main
      style={{
        maxWidth: 720,
        margin: "0 auto",
        padding: "4rem 1.5rem",
      }}
    >
      <h1 style={{ margin: 0, fontSize: "2.5rem" }}>TanStack Start</h1>
      <p style={{ marginTop: "1rem", fontSize: "1.125rem", lineHeight: 1.6 }}>
        This is the minimal app scaffold in{" "}
        <code>examples/cloudflare-tanstack</code>.
      </p>
      <p style={{ marginTop: "1rem", lineHeight: 1.6 }}>{data.message}</p>
      <p
        style={{
          padding: "0.75rem 1rem",
          background: "#e2e8f0",
          borderRadius: 8,
          fontFamily: "ui-monospace, SFMono-Regular, monospace",
        }}
      >
        {data.time}
      </p>
      <button
        type="button"
        onClick={async () => {
          setData(await getServerTime());
        }}
        style={{
          padding: "0.75rem 1rem",
          border: "none",
          borderRadius: 8,
          background: "#0f172a",
          color: "#fff",
          cursor: "pointer",
        }}
      >
        Refresh from server
      </button>
    </main>
  );
}
