// examples/cloudflare-tanstack/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { backend } from "../lib/backend.ts";

export const Route = createFileRoute("/")({
  // The isomorphic backend client: during SSR this is the value form
  // (direct in-process dispatch against src/backend.ts — no HTTP); on
  // client-side navigation it is the type-only form (POST /api/__rpc/visits).
  loader: async () => ({
    visits: await backend.visits(),
    processed: await backend.processed(),
  }),
  component: Home,
});

function Home() {
  const { visits, processed: initialProcessed } = Route.useLoaderData();
  const [bumped, setBumped] = useState<number | null>(null);
  const [processed, setProcessed] = useState(initialProcessed);
  const [queueText, setQueueText] = useState("");

  // The async leg: enqueue a message, then poll processed() so the
  // consumer's catch-up is visible (bounded — stop once count grows).
  async function sendToQueue() {
    const before = (await backend.processed()).count;
    await backend.enqueue(queueText || "hello queue");
    for (let i = 0; i < 15; i++) {
      await new Promise((resolve) => setTimeout(resolve, 1000));
      const p = await backend.processed();
      setProcessed(p);
      if (p.count > before) break;
    }
  }

  return (
    <main className="mx-auto max-w-2xl p-8">
      <h1 className="text-3xl font-bold">TanStack Start on Cloudflare Workers</h1>
      <div className="mt-6 max-w-md rounded-xl border border-slate-300 bg-white p-6 shadow-sm">
        <p className="m-0 text-sm text-gray-500">
          Server-rendered visits: <span data-testid="count">{visits}</span>
        </p>
        <button
          type="button"
          className="mt-4 cursor-pointer rounded-lg bg-slate-900 px-4 py-2 text-white"
          onClick={async () => {
            // Client-side: POST /api/__rpc/bump — typed, no fetch code.
            setBumped(await backend.bump());
          }}
        >
          Bump visits
        </button>
        {bumped !== null && (
          <p className="mt-4 text-sm" data-testid="bumped">
            Client bump → {bumped}
          </p>
        )}
      </div>
      <div className="mt-6 max-w-md rounded-xl border border-slate-300 bg-white p-6 shadow-sm">
        <input
          className="w-full rounded-lg border border-slate-300 px-3 py-2"
          placeholder="hello queue"
          value={queueText}
          onChange={(e) => setQueueText(e.target.value)}
        />
        <button
          type="button"
          className="mt-4 cursor-pointer rounded-lg bg-slate-900 px-4 py-2 text-white"
          onClick={sendToQueue}
        >
          Send to queue
        </button>
        <p className="mt-4 text-sm text-gray-500" data-testid="processed">
          Queue-processed:{" "}
          <span data-testid="processed-count">{processed.count}</span> — last:{" "}
          <span data-testid="processed-last">{processed.last ?? "—"}</span>
        </p>
      </div>
    </main>
  );
}

// examples/aws-website-sveltekit/src/routes/+page.svelte
<script lang="ts">
  // Browser side: TYPE-ONLY import + type-only form — zero backend bytes
  // in the client bundle. Each call POSTs the wire protocol
  // (`/api/__rpc/bump`) to the same Lambda. The SSR value arrives via
  // +page.server.ts, which calls `visits()` in-process (value form).
  import { createClient } from "alchemy/Client";
  import type Backend from "../backend.ts";

  const backend = createClient<typeof Backend>();

  let { data } = $props();
  let bumped = $state<number | null>(null);

  async function bump() {
    bumped = await backend.bump();
  }

  // The async leg: `enqueue` sends to SQS and returns immediately — the
  // sibling consumer Lambda catches up out of band. Poll `processed()`
  // (bounded) until the count moves so the catch-up is visible.
  let queueText = $state("");
  let processed = $state(data.processed);

  async function enqueue() {
    const before = processed.count;
    await backend.enqueue(queueText || "hello queue");
    for (let i = 0; i < 15; i++) {
      await new Promise((resolve) => setTimeout(resolve, 1000));
      processed = await backend.processed();
      if (processed.count > before) break;
    }
  }
</script>

<main class="mx-auto max-w-2xl p-8">
  <div class="rounded-xl border border-slate-200 bg-white p-8 shadow-sm">
    <h1 class="text-3xl font-bold">SvelteKit on AWS</h1>
    <p class="mt-4">
      Server-rendered visits: <span id="visits" class="font-semibold">{data.visits}</span>
    </p>
    <button
      class="mt-2 rounded border border-slate-300 px-3 py-1 hover:bg-slate-100"
      onclick={bump}
    >
      Bump visits
    </button>
    {#if bumped !== null}
      <p class="mt-2">Client bump → <span class="font-semibold">{bumped}</span></p>
    {/if}
    <div class="mt-6 border-t border-slate-200 pt-4">
      <div class="flex gap-2">
        <input
          class="rounded border border-slate-300 px-3 py-1"
          placeholder="hello queue"
          bind:value={queueText}
        />
        <button
          class="rounded border border-slate-300 px-3 py-1 hover:bg-slate-100"
          onclick={enqueue}
        >
          Send to queue
        </button>
      </div>
      <p class="mt-2">
        Queue-processed: <span class="font-semibold">{processed.count}</span>
        — last: <span class="font-semibold">{processed.last ?? "—"}</span>
      </p>
    </div>
    <p class="mt-4">
      <a class="underline" href="/about">about (prerendered)</a>
    </p>
  </div>
</main>
