// examples/cloudflare-website-nuxt/app/pages/about.vue
<template>
  <main class="mx-auto max-w-2xl p-8">
    <h1 class="text-3xl font-bold tracking-tight">About</h1>
    <p class="mt-2 text-muted-foreground">
      This page is prerendered at build time and served as a static asset.
    </p>
    <NuxtLink
      class="mt-6 inline-block text-sm underline underline-offset-4"
      to="/"
    >
      home
    </NuxtLink>
  </main>
</template>

// examples/cloudflare-website-waku/src/pages/about.tsx
export default function AboutPage() {
  return (
    <div className="flex flex-col gap-2">
      <h1 className="text-3xl font-bold tracking-tight">About</h1>
      <p className="text-muted-foreground">
        This page is prerendered at build time (SSG) and served as a static
        asset.
      </p>
    </div>
  );
}

// Static: rendered at build time by waku's SSG step and served from assets.
export const getConfig = async () => ({ render: "static" }) as const;
